### ISSUE TITLE
Warning: Use of undefined constant IMAGE_DERIVATIVE_TOKEN

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/insert#14]
The module causes the following error:

`
Warning: Use of undefined constant IMAGE_DERIVATIVE_TOKEN - assumed 'IMAGE_DERIVATIVE_TOKEN' (this will throw an Error in a future version of PHP) in template_preprocess_image_insert_image() (line 65 of /home/username/public_html/modules/insert/includes/image.inc).
`

**Comment by herbdool** [comment]
@alanmels are you interested in adopting this module as maintainer? There is no maintainer anymore. I don't use it and the last maintainer left.

**Comment by alanmels** [comment]
At some point I might, however for at least couple more months I'll be super busy.

**Comment by jromine** [comment]
Image tokens were not implemented in Backdrop as they were in Drupal 7.20. Per @klonos @BWPanda in https://github.com/backdrop/backdrop-issues/issues/3989, it is safe to remove that entire conditional in https://github.com/backdrop-contrib/insert/blob/43f9156db060efb2962b8d4143c758a0e5895b09/includes/image.inc#L63

**Comment by muranod** [comment]
Just encountered this as well. :-( Unfortunately, I'm not a coder.)
