### ISSUE TITLE
Offer to maintain this project

### ISSUE THREAD

**Issue by jromine** [backdrop-contrib/insert#17]
I'd like to offer to help maintain this project. I use this module on Drupal and Backdrop sites.  There is no current maintainer.  I will submit a PR adding my name as a maintainer.

**Comment by oadaeh** [comment]
@jromine, according to https://backdropcms.org/user-guide/adopt-a-project, the next step is to "[Create a separate issue](https://github.com/backdrop-ops/contrib/issues/new?assignees=klonos&labels=Maintainer+application&template=maintainer-applicatio) in the backdrop contrib queue asking to be added as a maintainer." I'm only seeing an old one in that queue, so I'm guessing you haven't done it yet. That might speed things along.

**Comment by jromine** [comment]
@oadaeh I submitted this one https://github.com/backdrop-ops/contrib/issues/624 (also linked above) is it not in the correct queue?

**Comment by oadaeh** [comment]
Ah, it did not show up with the terms I was using to search. Yes, that is correct.

**Comment by klonos** [comment]
Approved and merged. Thank you @jromine and sorry for not actioning this earlier.

PS: it is always a good idea to be pinging the Bug Squad in Zulip 😉
