### ISSUE TITLE
Full release?

### ISSUE THREAD

**Issue by jlfranklin** [backdrop-contrib/insert#2]
What would be needed to cut a proper release of this module?

**Comment by herbdool** [comment]
I actually don't know. I ended up not using it. Do you want to give it a spin and/or be added as maintainer? 

I can try it out when I get a chance. I don't see any tests on the module sadly.

**Comment by jlfranklin** [comment]
I'm using it on a client's site now.  I'll let you know how it turns out.

**Comment by Al-Rozhkov** [comment]
I'm using it on several sites and didn't face any issue. Let's make it available for everybody.

**Comment by herbdool** [comment]
I'll make a release. I'm updating the README to say that this module needs maintainers, since I'm not using it and don't wish to maintain it.

**Comment by klonos** [comment]
@herbdool I've filed a new 1.x-1.0.1 release because 1.x-1.0.0 was missing `type = module` from the .info file. I hope you don't mind.
