### ISSUE TITLE
Download link for 1.x-1.1.0 doesn't work

### ISSUE THREAD

**Issue by Radcliffe** [backdrop-contrib/insert#21]
The download link on the [project page](https://backdropcms.org/project/insert) for the current release (1.x-1.1.0) is not working.

**Comment by indigoxela** [comment]
@jromine it seems like the package for the latest release hasn't been created: https://github.com/backdrop-contrib/insert/releases/tag/1.x-1.1.0

I'd suggest to delete the release on Github and recreated it - and verify that this time the third asset (insert.zip) appears.

**Comment by jromine** [comment]
@indigoxela this is done.
