### ISSUE TITLE
Offer to maintain

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/insert#8]
I think I'd better offer to maintain this project, since I'm creating PRs and issues for it... :slightly_smiling_face:

**Comment by herbdool** [comment]
Yeah, I think you can adopt it! Create a PR putting your name into the README and I can merge it.

**Comment by ghost** [comment]
Here you go @herbdool https://github.com/backdrop-contrib/insert/pull/9

**Comment by herbdool** [comment]
Done
